"""Add password_hash column to applicants

Revision ID: 22e75735f614
Revises: 9f93bdb4e1de
Create Date: 2024-07-16 07:15:26.751257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e75735f614'
down_revision = '9f93bdb4e1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('password_hash', sa.String(length=128), nullable=True))

    op.execute("UPDATE applicants SET password_hash = 'default_password' WHERE password_hash IS NULL")

    with op.batch_alter_table('applicants') as batch_op:
        batch_op.alter_column('password_hash', existing_type=sa.String(length=128), nullable=False)

    op.drop_column('applicants', 'password')
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('applicants') as batch_op:
        batch_op.drop_column('password_hash')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('password', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('applicants', 'password_hash')
    # ### end Alembic commands ###
